export const ApiErrors: Record<number, string> = {
    1001: "Bot desconhecido",
    1002: "O bot já existe",
    1003: "Não foi possível obter os votos do bot",
    1004: "O usuário não é um bot",
    1005: "Um bot não pode votar em outro bot ou em si mesmo",
    1006: "Você está em cooldown, aguarde {ms}",
    1007: "Você não é o proprietário deste bot",
    2001: "Autenticador inválido",
    2002: "Algumas propriedades estão faltando",
    2003: "Muitas solicitações feitas em menos de 1 minuto",
    2004: "Erro de autenticação com o Discord",
    2005: "Nenhuma consulta foi fornecida no corpo",
    2006: "Ocorreu um erro interno no servidor, tente novamente",
    2050: "Sucesso!",
    2007: "Propriedade de usuário ausente",
    2008: "Algumas propriedades estão incorretas",
    2009: "Corpo ausente",
    2010: "Método não permitido",
    3001: "Guilda desconhecida",
    3002: "A guilda já existe",
    3003: "Você não é o proprietário desta guilda",
    4001: "O usuário já enviou o feedback",
    4002: "Feedback desconhecido",
    4003: "Não é possível enviar um feedback sem usuário",
    4050: "Este bot não possui feedbacks",
    4004: "Não é possível criar uma mensagem de resposta ao criar um feedback",
    5001: "Usuário desconhecido",
    5002: "Faltando ID de notificação",
    5003: "Notificação desconhecida",
    5004: "Este usuário não possui notificações",
    5005: "Apenas a chave 'bio' pode ser atualizada",
    5006: "O comprimento da biografia deve ser maior que 0 e menor que 200 caracteres",
    6001: "Equipe desconhecida",
    6002: "O usuário já tem uma equipe",
    6003: "O bot já pertence a uma equipe",
    6004: "Este bot não pode ingressar em uma equipe",
    6005: "O usuário não pertence a uma equipe",
    6006: "Você não pertence a esta equipe",
    6007: "Seu papel é somente leitura",
    6008: "Apenas o proprietário da equipe pode excluir a equipe",
    6009: "Convite inválido",
    6010: "O usuário já é um membro",
    6011: "O método GET não suporta o parâmetro de convite",
    6012: "Apenas o proprietário da equipe pode transferir a propriedade",
    6013: "O usuário não é um membro",
    6014: "Você não pode transferir a propriedade para si mesmo",
    6015: "Não é possível remover o proprietário da equipe",
    6016: "Você não pode se remover",
    6017: "Você não pode remover um administrador",
    6018: "Faltando 'member_id' no corpo para remover um membro"
};
